language: node_js
node_js:
- 12
services:
- postgresql
addons:
  postgresql: '10'
dist: xenial
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "acthub-test";' -U postgres
script:
- npm test
- webpack
branches:
  only:
  - master
  - staging
before_deploy:
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app:
    master: acthub
    staging: acthub-staging
  api_key:
    secure: WDup58m4CNSpcX6V1geYZSuSFAMR7q16KafmPqdCrzwRLCurOsdJkTJbsTML/4TWAZZeIev479GWyaY31jd+S5dYuCMlTP4esGUhNRu7gzWJ/Eg6uZqllX35Xgheicln4N7QphpLw5IIPaKxpXXZVquXM0W7BoOpFEqrMvBj7MztfNxnB+jPo7S+3KZCmJbal8NrATuT+NkL2gx2AiZTnPTbVbFLTp+YHjzeLl7qbEcp9C5Oj9EIJH/t/PoocgqnWYK9ZRLwGizE2ADlbrfqmDc8emtFyu1fyvOAmywQOewqfF3Sa3RyMYOV3gyL0nSAvTu7v+m6fT8GXto+VTFJH+xWucTGpb5PX3vr/vuGbQUwmVPBJ+XQcmyC0Q2qb4mivl0w7hD/jv1aZCJk5bHQUUvfJfnWDY56vw68PeTjVuf8hZgpJdufbDZlbyzNeLEh//v6DuAbLvB1KLwXGrGra6fU7isrg2LKfeE3y8ZwUNClqWMlgxY+ue/FMLkyKeup5waE2L6KkFqVIBc3STs7MwOH+MVqrahwXoDaSpYbuEEfB6W/E3CF3o5NJtnncRXKjKBZABLeVeS0FuB3xYDXDeTA2ssKkK5atEWP5Fjg9R5kwwgW3rHa+f2p6Wn4z5awt3FibD8VIuWhjLU+l7eUXmTH8LovgisZO7F87H4jmhU=
env:
  global:
    SESSION_SECRET:
      secure: vrRXPayJ9KzaEIHdnSznwsd5rYDIeCVHEmZ0TDONrDE2z3dVYJxdKEqNcLSouat6EswIPrdhL2GvyAZ3WX0XL/x1GFp4H048MBdSuj6u7hMfGV/Vk59GwTqx5/XZt6Z8WRCWzvqcicdB5fqwl/41czfSj0v2FcFB9uhfI/IoTG6Jq8x1AUh5iz20ZD9AQLrdVYtwFQgAzFuO8xOouWIU+FGYyjOUNu+y9+Abr769XV4ijH29zV6HKqpBHa0lPX66Kw9NbM1vTkAq+LSLaWuhVtQcg1IEQeyapjigxLMCZ4zW8Osn6D/OJbyC1MUUSxrY4hxCoVEzPtbqwpK8Yn36FjTn7AK19nGEAJADgAtDE2rfhcEz6rKW3BSuTMwUeMxFvMD82Js0uEgLv04IJRidjDM5zlyPqsac5xRPZq5gZpi8hoGdh4wCT6AE9XfOOW2TNDhW7WzeHo4nHclc3vuBskpknJUYR4BhWEH5YP0tm3cJS69p8FQCjuBltKy31lrdEgLQ0t71Y4JD0JbpdL1+SZwY6K4Fd3lwbWLSwlvonKkyb+7Y7PPIAKpG12AUcgmGLXGGIBl8rfIZQ4WrUoOjE+3v/gICJZPJztjTEuJpgxuvrIbgXWUslzShe+APlzJCJvAmqIWFqMHlpvxjEsHtUTyKjO+r1IFAVfk0V2h4dVI=
    GOOGLE_CLIENT_ID:
      secure: VF6Kus8daIBHR+tcVwFO9B9kaTVO5CertXSfLq1l1NXvobfJuMoA3/MB1kxuke9+Xgx86iOzJJ3PaG+eAmRJKxjh1DXE2PaabxOyeHN6CLaym9S5dvBlpVFK5yCq1BWvm3/jNre+LKXe19j9AoW50xySXtED/JP92gTX5xMTxxNF1FDuIqRXwrVy2EhQg8+jj9kOFcnviHdsolmt8LpZ9UtyNyp7rSdc8riCTHEu1wPuCCnRwsewG9E6u9PYYi97lP2fav7CJ6yIUajpEkrha+5SYSqR29Mo9RPvUIAryGdyVZOEGyZ8W2XKHGFs98F2BXMcIzWW0YVekjCOv0s6yEaXF5Miu63gQt8wZnZ5L0oVGjFYYo3uANxHIzS2AdztaMCVzQvVwVBLVpIb8g1f0pxlCJKfSPTYaUS91jUjwxG5lecae3TD6s0RdRmZxA2jh3WhUhz9RWjqcxlB/JCkeCBCnYMdPr/NMR1b4PLaJuf52mnJ1ZYS4J1y3F2D+h3IrvyiVWQV356p9IC9WeuBv3MTbG8+vE2IHQ5sKE0tZuunmGswPuo1OfOdkAHtCJaVOpp4SYad8ZweI7hrlMb3pIkXcSQ6R9AILXy0ixBClnVm32xH5rCyRiGerzYVQxQzkNjPZ6WFU1axlddMrrNNMaM3lLVtDooC7vSORWgbrrw=
    GOOGLE_CLIENT_SECRET:
      secure: EUgJYgeAQmHU4X2wWZZIbwQHaaSyLx45MMMN8h/D/T0+ylX63q0Xq0g7H8k3K8gioIdj5RjlBZPoqAsa/ofnbEuyZvUpklrZmuebk3LRtFfAveSf1HYphS5srG+fjoV6Pfi53vEZljpqna2YQR8WjG0BR7W1tTca6D4KQj6GiMzykS2xP7+GnQ6YFaJsga5pD1ez+B4u4WDkkdxbAeAFAdD0coxP88lc3ufeyY4t3Fz52xQDfOqjtJceB3XFb2c5krJisLquwFOjPEdi7iZ69Zc46lZKqv1xgAhwbcPDiiZCndWxvqoUz5EROAEb5gP486biUBQ8acjbPQYFIxbKJb+MhLjEROMf1HtJ/xxqiJp3zr/mk75VrjGj3Pa0nv/iGR13J/6ZTk23HY9bHvTbxAGAxLtK8GEbb+66P4p7DFQt0UYgiAGwBVeby/KjX9iXql+pdVwKssQWgGkOzOLX8XtYRSH7vuds0mslb83/P9xlqepawP1Wz+294wXDWyH6EoecQnSoRa5Pa+XAVCfTgDqLSrEGU37kVB0GUVM3AKRLtN6xaemZPX3Nmvh+JhD313vKQYqDq6kGZhJ5TkhSjYiLqjqZSNyo/+zRn9GhJNaAzsm45X5pOH6UzIhEQDSX46rilbkSWxrlL7/82MnssdRghI9BJEILI4Ff1wfd1uQ=
